### ISSUE TITLE
KongRoute's with headers are not accepted by Konnect

### ISSUE THREAD

**Issue by czeslavo** [Kong/kong-operator#1043]
## Current Behavior

`KongRoute` with the `spec.headers` field filled is not accepted by Konnect (while it's accepted by the Kubernetes API).
Konnect expects `map[string][]string` for the `headers` field while the SDK and Kubernetes CRD use `map[string]string`.

```terminal
Reconciler error - {"controller": "KongRoute", "controllerGroup": "configuration.konghq.com", "controllerKind": "KongRoute", "KongRoute": {"name":"service-2","namespace":"default"}, "namespace": "default", "name": "service-2", "reconcileID": "e38e825c-0040-4950-b777-59f2644e197f", "error": "failed to create KongRoute on Konnect: failed to create KongRoute default/service-2: API error occurred: Status 400\n{\"code\":3,\"message\":\"proto: syntax error (line 1:33): unexpected token \\\"value1\\\"\"}"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
	/Users/grzegorz.burzynski@konghq.com/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
	/Users/grzegorz.burzynski@konghq.com/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
	/Users/grzegorz.burzynski@konghq.com/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:224
```

## Expected Behavior

Hot fix: don't change the CRD API. Fix the SDK type into `map[string][]string`. Transform `map[string]string` into `map[string][]string` in KGO.

## Steps To Reproduce

```yaml
kind: KongService
apiVersion: configuration.konghq.com/v1alpha1
metadata:
  name: service-2
  namespace: default
spec:
  name: service-2
  host: example.com
  controlPlaneRef:
    type: konnectNamespacedRef
    konnectNamespacedRef:
      name: cp-to-be-referred-by-id
---
kind: KongRoute
apiVersion: configuration.konghq.com/v1alpha1
metadata:
  name: service-2
  namespace: default
spec:
  name: route-1
  headers:
    header1: value1 
  protocols:
  - http
  hosts:
  - example.com
  serviceRef:
    type: namespacedRef
    namespacedRef:
      name: service-2
```

## Operator Version

v1.4.1

**Comment by jaskeerat789** [comment]
Hey Folks, we are being affected by this. Is there a timeline on when can we see a fix being rolled out for the same ?

**Comment by czeslavo** [comment]
> Hey Folks, we are being affected by this. Is there a timeline on when can we see a fix being rolled out for the same ?

Hi @jaskeerat789, we most likely will release a patch version with a fix for this today or tomorrow.

**Comment by jaskeerat789** [comment]
Thanks @czeslavo

**Comment by czeslavo** [comment]
`kong/gateway-operator` Helm chart including the CRD fix was released: https://github.com/Kong/charts/releases/tag/gateway-operator-0.4.7 

If you had an existing installation, [please update CRDs manually](https://github.com/Kong/charts/blob/5bf6276477c9e01de3d4c24268770ab267e7558b/charts/gateway-operator/UPGRADE.md#L27) as Helm charts don't do that automatically on chart upgrade. The fix is included in v1.0.8 of the CRDs. The command for updating CRDs:

```console
kustomize build github.com/Kong/kubernetes-configuration/config/crd/gateway-operator?ref=v1.0.8 | kubectl apply -f -
```

Please also make sure that your manager's image version is updated to the latest v1.4.2 patch (add `--set image.tag=1.4.2`) to your `helm upgrade` command.

The API changed so that now it's possible to set multiple header values for a single header key (KongRoute's `spec.headers` changed from `map[string]string` to `map[string][]string`). An example:

```yaml
kind: KongRoute
apiVersion: configuration.konghq.com/v1alpha1
metadata:
  name: route-with-service
  namespace: default
spec:
  name: route-with-service
  protocols:
  - http
  hosts:
  - example.com
  headers:
    TestHeader:
      - value1
      - value2
  serviceRef:
    type: namespacedRef
    namespacedRef:
      name: service
```
