### ISSUE TITLE
Panic Error - KGO with a KIC cluster type

### ISSUE THREAD

**Issue by AntoineJac** [Kong/kong-operator#1112]
## Current Behavior

Hi team, when using a KIC CP with the KGO, the CP setup in Konnect is read-only.
A client should normally using the KIC to reconcile CRDs and not able to use KGO.
However if we are creating a `KongService` and set a spec.controlPlaneRef with the KIC CP, KGO is panicking

## Expected Behavior
KGO should not allow and skip trying to reconcile a KongService if cluster type is KIC

## Steps To Reproduce

```
echo '
kind: KonnectAPIAuthConfiguration
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: konnect-api-auth
  namespace: default
spec:
  type: token
  token: kpat_XXXX
  serverURL: eu.api.konghq.com
' | kubectl apply -f -
```

```
echo '
kind: KonnectGatewayControlPlane
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: kic-control-plane
  namespace: default
spec:
  name: kic-control-plane # Name used to identify the Gateway Control Plane in Konnect
  cluster_type: CLUSTER_TYPE_K8S_INGRESS_CONTROLLER # Type of the Gateway Control Plane
  konnect:
    authRef:
      name: konnect-api-auth # Reference to the KonnectAPIAuthConfiguration object
  ' | kubectl apply -f -
```

```
echo '
kind: KongService
apiVersion: configuration.konghq.com/v1alpha1
metadata:
  name: service
  namespace: default
spec:
  name: service
  host: example.com
  controlPlaneRef:
    type: konnectNamespacedRef # This indicates that an in cluster reference is used
    konnectNamespacedRef:
      name: kic-control-plane
  ' | kubectl apply -f -
```

You will get the error:

```
{
  "level": "error",
  "ts": "2025-01-30T19:19:11Z",
  "msg": "Reconciler error",
  "controller": "KongService",
  "controllerGroup": "configuration.konghq.com",
  "controllerKind": "KongService",
  "KongService": {
    "name": "service",
    "namespace": "default"
  },
  "namespace": "default",
  "name": "service",
  "reconcileID": "2c09c878-cb77-4110-969d-331ceef6386e",
  "error": "panic: runtime error: invalid memory address or nil pointer dereference [recovered]",
  "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.0/pkg/internal/controller/controller.go:332\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.0/pkg/internal/controller/controller.go:279\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.0/pkg/internal/controller/controller.go:240"
}
{
  "level": "error",
  "ts": "2025-01-30T19:19:11Z",
  "logger": "KongService",
  "msg": "operation in Konnect API failed",
  "controller": "KongService",
  "controllerGroup": "configuration.konghq.com",
  "controllerKind": "KongService",
  "KongService": {
    "name": "service",
    "namespace": "default"
  },
  "namespace": "default",
  "name": "service",
  "reconcileID": "cce51d9f-4519-41cf-8132-46dc68aeaca1",
  "op": "create",
  "duration": "18.125µs",
  "error": "can't create KongService default/service without a Konnect ControlPlane ID"
}
{
  "level": "error",
  "ts": "2025-01-30T19:19:11Z",
  "msg": "Observed a panic",
  "controller": "KongService",
  "controllerGroup": "configuration.konghq.com",
  "controllerKind": "KongService",
  "KongService": {
    "name": "service",
    "namespace": "default"
  },
  "namespace": "default",
  "name": "service",
  "reconcileID": "cce51d9f-4519-41cf-8132-46dc68aeaca1",
  "panic": "runtime error: invalid memory address or nil pointer dereference",
  "panicGoValue": "\"invalid memory address or nil pointer dereference\"",
  "stacktrace": "runtime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:900\ngithub.com/kong/gateway-operator/controller/konnect.(*KonnectEntityReconciler[...]).Reconcile\n\t/home/runner/go/pkg/mod/github.com/kong/gateway-operator@v1.4.2/controller/konnect/reconciler_generic.go:512\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.0/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.0/pkg/internal/controller/controller.go:319\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.0/pkg/internal/controller/controller.go:279\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.0/pkg/internal/controller/controller.go:240"
}
```

## Operator Version
KGO 1.4

## `kubectl version`
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
