### ISSUE TITLE
Properly handle Gateway spec changes that make the Gateway unaccepted

### ISSUE THREAD

**Issue by mlavacca** [Kong/kong-operator#126]
## Problem Statement

In the scenario where a Gateway has been properly created and is accepted, KGO creates a DataPlane and a ControlPlane. In case the Gateway spec changes and the user introduces a misconfiguration, KGO does not properly handle the consequences on CP and DP. We should add two different logic in the operator:

- improve the admission webhook to block spec changes that make the Gateway unaccepted once it is already programmed, to avoid users shutting down CP and DP because of a configuration error.
- properly delete the CP and DP in the Gateway Controller in case the Gateway is misconfigured. This never happens in case the webhook is active (the change is blocked).

## Acceptance Criteria

- [ ] in the webhook, in case a Gateway is already programmed, reject any Gateway update that makes the Gateway unaccepted
- [ ] in the controller, properly delete all the resources owned by an unaccepted Gateway.

**Comment by shaneutt** [comment]
It's not super relevant, but I think https://github.com/Kong/gateway-operator/issues/1444 is at least a bit tangentially related in that it deals with situations where the `Gateway` would no longer be accepted. It might be worth solving both in one shot if it's straightforward enough?

**Comment by mlavacca** [comment]
> It's not super relevant, but I think Kong/gateway-operator#132 is at least a bit tangentially related in that it deals with situations where the `Gateway` would no longer be accepted. It might be worth solving both in one shot if it's straightforward enough?

I think it makes sense to look at both the issues and see if they can be solved in one shot. I'm not sure if it's feasible now, we should evaluate when fixing the issue

**Comment by pmalek** [comment]
Assigning @mlavacca to post an exemplar config (manifest) which would cause this failure mode and discuss with product on direction forward for this (webhook rejection or other mechanism).

**Comment by pmalek** [comment]
@mlavacca unassigning you.

In case you have the manifest mentioned above please attach it to the issue.

**Comment by mlavacca** [comment]
In order to trigger this behavior, run the following commands:

Creates a Gateway that gets accepted by KO:

```bash
cat <<EOF | k apply -f -
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: test
spec:
  controllerName: konghq.com/gateway-operator
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
  namespace: default
spec:
  gatewayClassName: test
  listeners:
  - name: http
    protocol: HTTP
    port: 80
EOF
```

inspect the Accepted condition:

```yaml
  - lastTransitionTime: "2026-06-10T09:07:09Z"
    message: All listeners are accepted.
    observedGeneration: 1
    reason: Accepted
    status: "True"
    type: Accepted
```

Then, updates the Gateway's listener to make it unaccepted:

```bash
cat <<EOF | k apply -f -
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
  namespace: default
spec:
  gatewayClassName: test
  listeners:
  - name: http
    protocol: SCTP
    port: 80
EOF
```

inspect the Accepted condition:

```yaml
  - lastTransitionTime: "2026-06-10T09:07:28Z"
    message: Listener 0 is not accepted.
    observedGeneration: 2
    reason: ListenersNotValid
    status: "False"
    type: Accepted
```

cc @pmalek
