### ISSUE TITLE
invalid: spec.externalTrafficPolicy: Invalid value: \"Cluster\"

### ISSUE THREAD

**Issue by wssaidong** [Kong/kong-operator#1431]
## Current Behavior

│ {"level":"error","ts":"2025-04-01T18:57:18Z","msg":"Reconciler error","controller":"dataplane","controllerGroup":"gateway-operator.konghq.com","controllerKind"
│ :"DataPlane","DataPlane":{"name":"dataplane-example","namespace":"kong"},"namespace":"kong","name":"dataplane-example","reconcileID":"da146969-dbd6-4c26-b41f-4
│ 898e80fb082","error":"Service \"dataplane-ingress-dataplane-example-f9cx7\" is invalid: spec.externalTrafficPolicy: Invalid value: \"Cluster\": may only be set
│  for externally-accessible services","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/g
│ o/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:341\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller
│ ...[]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:288\nsigs.k8s.io/controller-
│ runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/cont
│ roller.go:249"}
│

## Steps To Reproduce

```
apiVersion: gateway-operator.konghq.com/v1beta1
kind: DataPlane
metadata:
  name: dataplane-example
  namespace: kong
spec:
  network:
    services:
      ingress:
        type: ClusterIP
  deployment:
    podTemplateSpec:
      spec:
        containers:
          - name: proxy
            image: kong/kong-gateway:3.9.1.1
```

## Operator Version
1.5

## `kubectl version`
Client Version: v1.30.7
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.7+orb1
