### ISSUE TITLE
Support imagePullSecrets in CRD DataPlane gateway-operator.konghq.com/v1beta1

### ISSUE THREAD

**Issue by maclermo** [Kong/kong-operator#1464]
## Problem Statement

Right now, the CRD or kind DataPlane does not support setting imagePullSecrets in its spec.deployment as an option.

## Proposed Solution

Add support for spec.deployment.imagePullSecrets so that data planes can be started with a private registry. The resulting Deployment must include spec.template.spec.imagePullSecrets[*].name with the values.

## Additional Information

Using latest Helm Chart release: gateway-operator-0.5.4 and deploying the docker image kong/gateway-operator version 1.5

## Acceptance Criteria
- [ ] Must provide a way to set imagePullSecrets in the CRD of kind DataPlane
- [ ] Must update docs with the new imagePullSecrets option

**Comment by pmalek** [comment]
@maclermo 👋 

You can achieve this by setting the `imagePullSecrets` under `spec.deployment.podTemplateSpec.spec` like so:

```
apiVersion: gateway-operator.konghq.com/v1beta1
kind: DataPlane
metadata:
  name: dataplane-example
spec:
  deployment:
    podTemplateSpec:
      spec:
        imagePullSecrets:
        - name: pullsecret1
        containers:
        - name: proxy
          image: patrykmalekkonghq/kong:3.11 # private version of kong 3.11
```

Just tested this with KGO 1.6.

Created the secret like so:

```
k create secret docker-registry pullsecret1 --docker-server=docker.io --docker-username=USERNAME --docker-password=dckr_pat_XXXXXXXXXXXXXXXXXXXXXXXXXXX --docker-email=MYEMAIL@DOMAIN.COM
```

Let us know if you have any other questions on this.
