### ISSUE TITLE
Gateway: support for DataPlane's HPA

### ISSUE THREAD

**Issue by amontalban** [Kong/kong-operator#1486]
## Problem Statement

When using `GatewayConfiguration` is not possible to configure `DataPlane`'s HPA as it is possible if you define the `DataPlane` directly as shown in the [docs](https://docs.konghq.com/gateway-operator/latest/guides/autoscaling-kong/).

This is super important when dealing with multiple `Gateway`s so you ensure all of them are configured equally.

## Proposed Solution

Allow user to configure HPA in the `GatewayConfiguration` as described for PDBs in #469.

## Additional Information

...

## Acceptance Criteria
- [ ] Lorem ipsum dolor sit amet

**Comment by pmalek** [comment]
This is already possible. You can use the following manifest to achieve this:

```
kind: GatewayConfiguration
apiVersion: gateway-operator.konghq.com/v1beta1
metadata:
  name: kong
  namespace: default
spec:
  dataPlaneOptions:
    deployment:
      scaling:
        horizontal:
          minReplicas: 2
          maxReplicas: 10
          metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 50
          behavior:
            scaleDown:
              stabilizationWindowSeconds: 1
              policies:
              - type: Percent
                value: 100
                periodSeconds: 2
            scaleUp:
              stabilizationWindowSeconds: 1
              policies:
              - type: Percent
                value: 100
                periodSeconds: 2
              - type: Pods
                value: 5
                periodSeconds: 2
              selectPolicy: Max
      podTemplateSpec:
        spec:
          containers:
          - name: proxy
            # renovate: datasource=docker versioning=docker
            image: kong/kong-gateway:3.10
            readinessProbe:
              initialDelaySeconds: 1
              periodSeconds: 1
  controlPlaneOptions:
    deployment:
      podTemplateSpec:
        spec:
          containers:
          - name: controller
            env:
            - name: CONTROLLER_LOG_LEVEL
              value: debug
---
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: kong
spec:
  controllerName: konghq.com/gateway-operator
  parametersRef:
    group: gateway-operator.konghq.com
    kind: GatewayConfiguration
    name: kong
    namespace: default
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: kong
  namespace: default
spec:
  gatewayClassName: kong
  listeners:
  - name: http
    protocol: HTTP
    port: 80
```


#1558 adds an official sample to use.

To use that please ensure you're using the supported version of kubernetes-configuration: https://docs.konghq.com/gateway-operator/latest/reference/version-compatibility/#kubernetes-configuration-crds.

Closing as there's nothing to be done in the operator.
