### ISSUE TITLE
`PodTemplateSpec` patch mechanism needs to know the base manifest to know which default to fill in

### ISSUE THREAD

**Issue by pmalek** [Kong/kong-operator#150]
### Problem statement

Leftover from Kong/gateway-operator-archive#904 and Kong/gateway-operator-archive#1224.

When filling in the defaults in `PodTemplateSpec` patch there are some exceptions that we need to pay attention to: e.g. when adding volumes, we need to add the original element(s) of the array to not everwrite (or rather make the patch blend in) the base with the patch. This causes the following:

```
        volumes:
        - name: cluster-certificate # We need this, otherwrite strategic merge patch will merge and mangle this - from the base manifest - with the specified first element.
        - name: konnect-client-tls
          secret:
            secretName: konnect-client-tls
```

This has a consequence: when specifying the element in the patch we don't specify the type of the volume, hence the [defaulting mechanism](https://github.com/Kong/gateway-operator/blob/3e42b2ca16899475ae9cc26a6d8d293a5ce40648/internal/utils/kubernetes/resources/strategicmerge.go#L72-L103) will set the `EmptyDir` field's values in `Volume` via [`SetDefaults_Volume`](https://github.com/kubernetes/kubernetes/blob/2b69daa960ccea9a19f58e73a9079db94bc0819d/pkg/apis/core/v1/defaults.go#L66-L72). This in turn is in conflict with the base manifest (generated by e.g. [`GenerateNewDeploymentForDataPlane()`](https://github.com/Kong/gateway-operator/blob/3e42b2ca16899475ae9cc26a6d8d293a5ce40648/internal/utils/kubernetes/resources/deployments.go#L154)) which uses secret volume source. This then yields an error during the `Patch` operation:

```
[spec.template.spec.volumes[0].secret: Forbidden: may not specify more than 1 volume type
```

A stopgap solution has been introduced in Kong/gateway-operator-archive#1224 to prevent the above from happening by checking if the Volume that we want to patch has a name used by both `ControlPlane`s and `DataPlane`s to hold the certificate (the only volume used in generated manifests).

This issue tracks the effort to overcome this "stopgap" and perhaps introduce a better, long term solution
