### ISSUE TITLE
Support TCPRoute  and custom TCP listener ports in Kong Gateway Operator

### ISSUE THREAD

**Issue by driosalido** [Kong/kong-operator#1510]
## Problem Statement

Kong Gateway Operator (tested with **v1.5.1**) cannot expose custom TCP listeners through Gateway API resources.  
Creating a `Gateway` listener with `protocol: TCP` and `port: 9000` makes the controller set the listener condition to **`UnsupportedProtocol`**, and the generated `DataPlane` Service does **not** open port 9000.  
In contrast, Kong Ingress Controller (KIC) handles the same use‑case today by:

1. Enabling a stream port in the Helm values.  
2. Deploying a `TCPIngress` that targets the backend service.

The gap prevents users from migrating workloads that rely on raw‑TCP proxying from KIC to the operator.

## Proposed Solution

1. **Add first‑class support for `TCPRoute`** in the operator.  
2. When a `Gateway` listener with `protocol: TCP` is present, reconcile the `DataPlane` Deployment so that it:
   * Adds the port to the proxy container via `KONG_PROXY_LISTEN` (or an equivalent env var).  
   * Exposes the port in the `DataPlane` ingress `Service`.  
3. Populate the usual Gateway API status fields (`Accepted`, `Programmed`, etc.) for both the `Gateway` listener and related `TCPRoute`.

## Additional Information

* Operator version tested: **v1.5.1** 
* Steps to reproduce:
  1. Install Gateway API CRDs (standard _plus_ experimental channel to obtain `TCPRoute` v1alpha2).
  2. Deploy Gateway Operator with default settings.
  3. Apply the manifest
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kong
spec:
  gatewayClassName: kong
  listeners:
  - name: tcp9000
    protocol: TCP
    port: 9000
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: echo-plaintext
spec:
  parentRefs:
  - name: kong
  rules:
  - backendRefs:
    - name: echo
      port: 1025
```
  4. Run  
     ```bash
     kubectl get svc -l app.kubernetes.io/component=dataplane-ingress
     ```  
     and observe the `UnsupportedProtocol` listener status and the absence of port 9000 in the Service definition.

## Acceptance Criteria
- [ ] A user can define a `Gateway` listener with `protocol: TCP` and expose arbitrary ports.  
- [ ] A `TCPRoute` attaches successfully; traffic on the listener is proxied to the backend Service.  
- [ ] The generated `DataPlane` Service contains the requested TCP port(s).  
- [ ] Implementation passes all relevant Gateway API conformance tests for `TCPRoute`.
