### ISSUE TITLE
Custom ingress service name in GatewayConfiguration is not respected

### ISSUE THREAD

**Issue by iron87** [Kong/kong-operator#1573]
## Current Behavior

When specifying a custom name under `GatewayConfiguration.dataPlaneOptions.network.services.ingress.name`, the generated service name does not reflect the configured value.  
For example, despite setting:

```yaml
dataPlaneOptions:
  network:
    services:
      ingress:
        name: my-gw-ingress
```

The resulting service name is:  
`dataplane-ingress-shared-gw-xh8lz-grch4`  
instead of the expected `my-gw-ingress`.

## Expected Behavior

The generated ingress service name should match the explicitly configured value, i.e., `my-gw-ingress`.

## Steps To Reproduce

1. Deploy a `GatewayConfiguration` with the following `dataPlaneOptions`:
   ```yaml
   dataPlaneOptions:
     network:
       services:
         ingress:
           name: my-gw-ingress
   ```
2. Deploy a `Gateway`
3. Note that the actual service name does not match the configured name.

## Operator Version

```
kgo     kong-system     1               2025-05-07 10:04:01.204411 +0200 CEST   deployed        gateway-operator-0.5.7  1.5
```

## `kubectl version`

```bash
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2
```
