### ISSUE TITLE
Konnect entities: handle `KonnectAPIAuthConfiguration` deletion

### ISSUE THREAD

**Issue by pmalek** [Kong/kong-operator#1586]
## Problem Statement

Currently, when working with Konnect entities, the resource holding the API authentication information - `KonnectAPIAuthConfiguration` - does not have any mechanisms in place which would prevent its deletion, before the deletion of resources that utilize the Konnect API.

Since objects mapping Konnect entities (like `KonnectGatewayControlPlane`) do have finalizers themselves, the effect is that `KonnectAPIAuthConfiguration` gets deleted but the Konnect entity resource remains with the following status condition:

```
    conditions:
    - lastTransitionTime: "2025-05-08T17:07:58Z"
      message: Referenced KonnectAPIAuthConfiguration / not found
      observedGeneration: 2
      reason: RefNotFound
      status: "False"
      type: APIAuthResolvedRef
```

## Proposed Solution

Add a `gateway.konghq.com/api-auth-in-use` finalizer to `KonnectAPIAuthConfiguration`s that are being used to prevent its deletion before all entities that use it get deleted first.

## Acceptance Criteria
- [ ] As a user I can delete a namespace which contains `KonnectAPIAuthConfiguration` as well Konnect resources using that auth configuration and can expect that the mapped Konnect entities will get deleted. After that happens all the resources and the `KonnectAPIAuthConfiguration` will get deleted, unblocking namespace deletion.
