### ISSUE TITLE
`instance_name` is not respected for KongPlugin on konnect

### ISSUE THREAD

**Issue by jaskeerat789** [Kong/kong-operator#1626]
## Current Behavior
Setting `instance_name` for a KongPlugin that bound to a KongService using KongPluginBinding or `konghq.com/plugins` annotation is not reflected on konnect dashboard.

## Expected Behavior
`instance_name` should be used to set Instance Name of plugin on konnect.

## Steps To Reproduce
1. Create a KongPlugin resource with `instance_name` field set.
2. Bind plugin to a resource
3. Check instance name field of plugin created on Konnect

## Operator Version
1.5.0

## `kubectl version`
Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.30.11-eks-bcf3d70

**Comment by jeffrey-arndt** [comment]
Ran a test in my lab for this. Confirmed KGO KongPluginBinding ignores the instance_name. This works in standard KIC + Konnect

```
---
kind: KongService
apiVersion: configuration.konghq.com/v1alpha1
metadata:
  name: service-1
  namespace: kgo-konnect
spec:
  name: service-1
  host: example.com
  controlPlaneRef:
    type: konnectNamespacedRef
    konnectNamespacedRef:
      name: gateway-control-plane
---
kind: KongRoute
apiVersion: configuration.konghq.com/v1alpha1
metadata:
  name: route-1
  namespace: kgo-konnect
  annotations:
    konghq.com/plugins: rate-limit-5-min
spec:
  name: route-1
  protocols:
  - http
  hosts:
  - example.com
  serviceRef:
    type: namespacedRef
    namespacedRef:
      name: service-1
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
 name: rate-limit-5-min
 namespace: kgo-konnect
config:
 minute: 5
 policy: local
plugin: rate-limiting
instance_name: jeffy-kgo-instance
---
apiVersion: configuration.konghq.com/v1alpha1
kind: KongPluginBinding
metadata:
  name: plugin-binding-kongservice-kongroute
  namespace: kgo-konnect
spec:
  controlPlaneRef:
    type: konnectNamespacedRef
    konnectNamespacedRef:
      name: gateway-control-plane
  pluginRef:
    name: rate-limit-5-min
  targets:
    serviceRef:
      name: service-1
      kind: KongService
      group: configuration.konghq.com
    routeRef:
      name: route-1
      kind: KongRoute
      group: configuration.konghq.com
```

![Image](https://github.com/user-attachments/assets/e4e205d9-953c-49c3-9e05-0d20f540a727)
