### ISSUE TITLE
Use ValidationAdmissionPolicy for validating objects on admission

### ISSUE THREAD

**Issue by pmalek** [Kong/kong-operator#167]
### Problem statement

With introduction of [`ValidatingAdmissionPolicy`](https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/)  (alpha in k8s 1.26, beta in 1.28, stable in 1.30) we could utilize this to reject invalid resources from admission.

For instance this policy could enforce `DataPlane`s to have an image specified:

```
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicy
metadata:
  name: dataplanes-have-image
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   ["gateway-operator.konghq.com"]
      apiVersions: ["v1beta1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["dataplanes"]
  validations:
    - expression: "has(object.spec.deployment.podTemplateSpec.spec) && object.spec.deployment.podTemplateSpec.spec.containers.exists_one(c, c.name == 'proxy' && has(c.image))"
      message: "DataPlane must specify its 'proxy' container image"
      reason: "Invalid"
---
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: dataplanes-have-image-binding
spec:
  policyName: dataplanes-have-image
  validationActions:
    - Deny
```
