### ISSUE TITLE
GatewayClass stuck at "Waiting for controller" with Kong Gateway Operator 1.6.x on Kubernetes 1.32.4

### ISSUE THREAD

**Issue by phoenix-pnp** [Kong/kong-operator#1697]
## Current Behavior

Any GatewayClass resource created (including minimal manifests) remains stuck with status:

```
status:
  conditions:
  - lastTransitionTime: "1970-01-01T00:00:00Z"
    message: Waiting for controller
    reason: Pending
    status: Unknown
    type: Accepted
```

The Kong Gateway Operator does not reconcile or update the GatewayClass. No relevant errors appear in the operator logs.

## Expected Behavior

The Kong Gateway Operator should reconcile the GatewayClass and update its status to Accepted: True, allowing Gateways to be provisioned.

## Steps To Reproduce

1. Install Kong Gateway Operator 1.6.x via Helm.
2. Apply Gateway API CRDs v1.3.0.
3. Create a minimal GatewayClass:
```
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kong-minimal
spec:
  controllerName: gateway-operator.konghq.com/gateway-operator
```
4. Observe that the status remains stuck at "Waiting for controller" and is never reconciled.

Additional notes:
- No relevant validating/mutating webhooks are present.
- RBAC and CRDs are correct and up-to-date.
- Operator pod is running and healthy.
- Tried different GatewayClass names and minimal manifests.
- No API server events for GatewayClass.

## Operator Version

Kong Gateway Operator: 1.6.1

## `kubectl version`
kubectl version
```
Client Version: v1.33.1
Kustomize Version: v5.6.0
Server Version: v1.32.4
```
---
Please let me know if you need any more details or logs!
