### ISSUE TITLE
KGO unexpectedly deletes and creates the 'gateway' TLS listener certificate each time data plane pods are rolled

### ISSUE THREAD

**Issue by pmalek** [Kong/kong-operator#1769]
### Problem statement

When KGO deployed KIC configures a Gateway with TLS listener certs like in the manifest below then each lifecycle event which causes the DataPlane Pods to cycle causes the certs to be deleted and recreated in Konnect.

```
kind: KonnectAPIAuthConfiguration
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: konnect-api-auth-dev-eu-1
  namespace: default
spec:
  type: token
  token: kpat_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  serverURL: eu.api.konghq.com
---
kind: KonnectGatewayControlPlane
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: gateway-control-plane
  namespace: default
spec:
  cluster_type: CLUSTER_TYPE_K8S_INGRESS_CONTROLLER
  name: gateway-control-plane # Name used to identify the Gateway Control Plane in Konnect
  konnect:
    authRef:
      name: konnect-api-auth-dev-eu-1 # Reference to the KonnectAPIAuthConfiguration object
---
kind: KonnectExtension
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: my-konnect-config
  namespace: default
spec:
  konnect:
    controlPlane:
      ref:
        type: konnectNamespacedRef
        konnectNamespacedRef:
          name: gateway-control-plane
  clientAuth:
    certificateSecret:
      provisioning: Automatic
---
kind: GatewayConfiguration
apiVersion: gateway-operator.konghq.com/v1beta1
metadata:
  name: kong
  namespace: default
spec:
  extensions:
    - kind: KonnectExtension
      name: my-konnect-config
      group: konnect.konghq.com
  dataPlaneOptions:
    deployment:
      podTemplateSpec:
        spec:
          containers:
          - name: proxy
            image: kong/kong-gateway:3.10
            readinessProbe:
              initialDelaySeconds: 1
              periodSeconds: 1
  controlPlaneOptions:
    deployment:
      podTemplateSpec:
        spec:
          containers:
          - name: controller
            env:
            - name: CONTROLLER_LOG_LEVEL
              value: trace
---
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: kong
spec:
  controllerName: konghq.com/gateway-operator
  parametersRef:
    group: gateway-operator.konghq.com
    kind: GatewayConfiguration
    name: kong
    namespace: default
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: kong
  namespace: default
spec:
  gatewayClassName: kong
  listeners:
  - name: http
    protocol: HTTP
    port: 80
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        group: ""
        name: cert1 # This cert has to be created separately using: kubectl create secret tls cert1 --cert=tls.crt --key=tls.key
```

### Anything else

Cross reference FTI-6783

### Acceptance criteria

- [ ] Cycling `DataPlane` Pods should not cause deletion and re-creating TLS `Gateway` listeners' certs.
