### ISSUE TITLE
GatewayConfiguration is not enforced after removing a customization field from it

### ISSUE THREAD

**Issue by pmalek** [Kong/kong-operator#190]
## Current Behavior

If user applies `GatewayConfiguration` with some customizations e.g. 

```yaml
kind: GatewayConfiguration
apiVersion: gateway-operator.konghq.com/v1alpha1
metadata:
  name: kong
  namespace: default
spec:
  dataPlaneDeploymentOptions:
    containerImage: kong
    version: "3.0.1"
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: kong
spec:
  controllerName: konghq.com/gateway-operator
  parametersRef:
    group: gateway-operator.konghq.com
    kind: GatewayConfiguration
    name: kong
    namespace: default
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: kong
spec:
  gatewayClassName: kong
  listeners:
  - name: http
    protocol: HTTP
    port: 80
```

and then removes e.g `version: "3.0.1"` from `dataPlaneDeploymentOptions` and applies it again the new configuration (without the version will have no effect i.e. `DataPlane` will remain at version `3.0.1` retaining "state" from previous configuration.

## Expected Behavior

Applying `GatewayConfiguration` should not have any state i.e. should not be dependant on any customizations applied before it. Applying the same config on fresh installation should have the same effect as applying it on an installation that was already customized.

## Steps To Reproduce

1. Apply this yaml

    ```yaml
    kind: GatewayConfiguration
    apiVersion: gateway-operator.konghq.com/v1alpha1
    metadata:
      name: kong
      namespace: default
    spec:
      dataPlaneDeploymentOptions:
        containerImage: kong
        version: "3.0.1"
    ---
    apiVersion: gateway.networking.k8s.io/v1beta1
    kind: GatewayClass
    metadata:
      name: kong
    spec:
      controllerName: konghq.com/gateway-operator
      parametersRef:
        group: gateway-operator.konghq.com
        kind: GatewayConfiguration
        name: kong
        namespace: default
    ---
    apiVersion: gateway.networking.k8s.io/v1beta1
    kind: Gateway
    metadata:
      name: kong
    spec:
      gatewayClassName: kong
      listeners:
      - name: http
        protocol: HTTP
        port: 80
    ```

1. Wait for the `Gateway` to be ready (together with DataPlane and ControlPlane)
1. Apply `GatewayConfiguration` stripped from the dataplane `version` customization

    ```yaml
    kind: GatewayConfiguration
    apiVersion: gateway-operator.konghq.com/v1alpha1
    metadata:
      name: kong
      namespace: default
    spec:
      dataPlaneDeploymentOptions:
        containerImage: kong
    ```

1. Observe no effect

## Operator Version

0de2346ea3361cacbcc1382a6fb017dbd77dba8c
