### ISSUE TITLE
Add fields for CRDs for adopting existing entities from Konnect

### ISSUE THREAD

**Issue by randmonkey** [Kong/kong-operator#2277]
## Problem Statement

From https://github.com/Kong/gateway-operator/issues/460 to adopt existing entities in Konnect. 

We should define fields in CRDs representing Konnect entities to specify attributes for adopting the entity from Konnect. The fields include the Konnect ID at least, and may include other specifications for adoption:

- How to adopt "immutable" entities like Konnect cloud gateway networks

## Proposed Solution

Add an `adopt` field under the spec of all the CRDs supporting to be adopted from Konnect.
Also we need to add at least the following rules on the field:
- Can only be present when the resource is configured to manage an entity in Konnect
- Be immutable when the resource is "Programmed", which means that the resource is already associated with a Konnect entity
- Add an interface to define resources that can adopt Konnect entity and implement the interface in the CRDs

## Acceptance Criteria

- [ ] `adopt.konnect.id` field present in all the CRDs that we want to support to adopt an entity from Konnect
- [ ] An interface to distinguish types that can adopt existing Konnect entities
  - [ ] The CRDs supporting adopting Konnect entities implements the interface
- [ ] Have the validation rules (CELs) to check the field
  - [ ] Cannot be added, modified or unset when the resource is "Programmed" (pointing to a Konnect entity)

**Comment by pmalek** [comment]
`konnect.entityID` might be a bit ambiguous: users might take it as "when creating this resource, set this ID".

How about:

```
spec:
  konnect:
    adopt:
      by: id # to allow interface extension in the future 
      id: <id_to_adopt>
```

or

```

spec:
  konnect:
    adoptId: <id_to_adopt>
```

WDYT?

**Comment by randmonkey** [comment]
I think the former one
```yaml
spec:
  konnect:
    adopt:
      by: id # to allow interface extension in the future 
      id: <id_to_adopt>
```
would make more sense, since @czeslavo has some thoughts of options of not changing the Konnect entity when it is not the same as the spec. This provides room for extensions.

**Comment by czeslavo** [comment]
How about making the strategy a parameter so it's clear what will be the behavior?

```yaml
spec:
  konnect:
    adoption: # to use nouns instead of verbs
      strategy: OverrideKonnectConfig # possible alternatives could be 'HaltOnKonnectConfigMismatch' or 'AdoptKonnectConfig'
      id: <id_to_adopt>
```
