### ISSUE TITLE
Controller wants to watch incorrect resource kind "aigatewaies"

### ISSUE THREAD

**Issue by jutley** [Kong/kong-operator#297]
## Current Behavior
Operator wants to watch resources named `aigatewaies`, an obvious misspelling of `aigateways`.

Also worth noting, I didn't even have the AIGateways feature enabled. I'm not sure why it tried to watch them.

## Expected Behavior
The resource is fetched and the pod can start up.

## Steps To Reproduce
Install the operator from the helm chart, and the pod will not report ready. Logs will show this:

```
{"level":"info","ts":"2024-05-28T18:09:14Z","logger":"setup","msg":"failed to create aigateway count provider","error":"GVR \"gateway-operator.konghq.com/v1alpha1, Resource=aigatewaies\" not available, reason: no matches for gateway-operator.konghq.com/v1alpha1, Resource=aigatewaies"}
```

## Operator Version
1.2.3

## `kubectl version`
```
→  kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.9
```

**Comment by pmalek** [comment]
The log entry is actually from the object counter for AIGateways and you can safely ignore that. Mark that it's logged on the info level. It doesn't affect Pod's readiness.

Other than that I'd look into the other logs so verify why your Pod didn't get ready. Can you attach those?

Also, please also include the deployment steps that you've used (helm? then please include the `values.yaml`).

**Comment by jutley** [comment]
I did use helm, using this operator as a subchart (so that we can add extra resources if needed). Here is the values file.

```yaml
---
gateway-operator:
  fullnameOverride: gateway-operator

  kubeRBACProxy:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 128Mi

  replicaCount: 1

  extraLabels: <redacted>

  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 256Mi

  env:
    METRICS_BIND_ADDRESS: :8080
    enable_controller_aigateway: "false"

```
