### ISSUE TITLE
the version of build-in chart is too old

### ISSUE THREAD

**Issue by morvencao** [Kong/kong-operator#4]
I tried to install kong with default parameters in OCP 4.3:
```
cat << EOF | oc apply -f -
apiVersion: charts.helm.k8s.io/v1alpha1
kind: Kong
metadata:
  name: kong-instance
  namespace: kong
spec:
```

And then tried some simple cases in https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/getting-started.md, looks like the `kong-plugin` never took effect.

However, if I I tried install with YAML manofests, everything is working fine.

```
kubectl apply -f https://bit.ly/kong-ingress-dbless
```

I compared the version and manifests generated, found the version of build-in helm chart is too old.

The build-in chart of kong operator is too old, currently the version:
- kong  `1.1` 
- kong-ingress-controller `0.3.0`.

I can see the the latest version is:
- kong version `2.0.2`
- kong-ingress-controller version `0.8.0`

I also tried install new version by customized the parameters for kong CR with current kong operator:

```
# cat << EOF | oc apply -f -
apiVersion: charts.helm.k8s.io/v1alpha1
kind: Kong
metadata:
  name: kong-instance
  namespace: kong
spec:
  ingressController:
    enabled: true
    image:
      repository: kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller
      tag: 0.8.0
  proxy:
    type: LoadBalancer
  # workaround for https://github.com/Kong/kong/issues/5708
  image:
    tag: 2.0.2
  # workaround for https://github.com/helm/charts/issues/12575
  env:
    pg_password: password
    database: postgres
  postgresql:
    enabled: true
    postgresqlUsername: kong
    postgresqlPassword: password
    postgresqlDatabase: kong
    service:
      port: 5432
EOF
kong.charts.helm.k8s.io/kong-instance created
```

And then found that `kong-ingress-controller` was always crashing because of incompatible CLI parameter: 
```
# oc logs -f kong-instance-dzxiztfn8k9p39fcapjh1isdj-kong-controller-7bmg5pm -c ingress-controller
-------------------------------------------------------------------------------
Kong Ingress controller
  Release:    0.8.0
  Build:      4b80e3f
  Repository: git@github.com:kong/kubernetes-ingress-controller.git
  Go:         go1.14.1
-------------------------------------------------------------------------------

unknown flag: --default-backend-service
Usage of :
unknown flag: --default-backend-service
```

My question is is there any plan to upgrade the kong operator? 

/cc @gyliu513 @zxdiscovery
