### ISSUE TITLE
Konnect entities: When deleting `KongService` with `KongRoute` attached, controller will try to delete the service in Konnect but fail

### ISSUE THREAD

**Issue by randmonkey** [Kong/kong-operator#777]
## Current Behavior

When a `KongService` has `KongRoute`s attached and we delete the `KongService`, the controller will try to delete the service on Konnect side, but the deletion will fail with the following response:
```
{"code":3,"message":"data constraint error","details":[{"@type":"type.googleapis.com/kong.admin.model.v1.ErrorDetail","type":"ERROR_TYPE_REFERENCE","messages":["constraint failed (type: foreign) as route references this value"]}]}
```
Then the controller will requeue the reconciliation request and try to delete the service endlessly.

## Expected Behavior

Do not fall into endless reconciliation errors or requeues. Possible ways to process:
- Run cascade delete on routes
- Reject the deletion of `KongSerive` that still have `KongRoute` attached to it
- Do not run deletion on Konnect for such `KongService`s

## Steps To Reproduce
(1) Create a `KongService`
(2) Create a `KongRoute` attached to the `KongService` by setting its `spec.ServiceRef`
(3) Delete the `KongService`

**Comment by pmalek** [comment]
I have tested that and it worked for me. The code for handling this case is in https://github.com/Kong/gateway-operator/blob/d9646df01407057d341437ce2ec7b1e75b57d8ec/controller/konnect/reconciler_generic.go#L159-L173 which deletes the `KongRoute` that references the `KongService` with a non zero deletion timestamp.

Can you provide concrete steps for reproducing this @randmonkey ?

**Comment by randmonkey** [comment]
@pmalek The reproducing steps: create `KongService` and `KongRoute` then delete `KongService`. Your step is deleting `KongRoute`.
(1) Create `KongService` and `KongRoute`

```
echo 'kind: KongService
apiVersion: configuration.konghq.com/v1alpha1
metadata:
  name: service-1
  namespace: default  
spec:
  name: service-1
  host: example.com
  controlPlaneRef:
    type: konnectNamespacedRef
    konnectNamespacedRef:
      name: test1
---
kind: KongRoute
apiVersion: configuration.konghq.com/v1alpha1
metadata:
  name: route-1
  namespace: default
spec:
  name: route-1
  protocols:
  - http
  hosts:
  - example.com
  serviceRef:
    type: namespacedRef
    namespacedRef:
      name: service-1' | kubectl apply -f -
```
(2) delete `KongService`
`kubectl delete kongservice service-1`

**Comment by pmalek** [comment]
> Your step is deleting KongRoute.

In my tests I have been deleting `KongService`. Please find the attached script that I've used to try to reproduce it.


```
#!/bin/bash

NAMESPACE=default

kubectl apply -f - <<EOF
kind: KongService
apiVersion: configuration.konghq.com/v1alpha1
metadata:
  name: test1
  namespace: ${NAMESPACE}
spec:
  name: test1
  host: example.com
  controlPlaneRef:
    type: konnectNamespacedRef
    konnectNamespacedRef:
      name: test1
---
kind: KongRoute
apiVersion: configuration.konghq.com/v1alpha1
metadata:
  name: test1
  namespace: ${NAMESPACE}
spec:
  name: test1
  protocols:
  - http
  hosts:
  - example1.com
  serviceRef:
    type: namespacedRef
    namespacedRef:
      name: test1
EOF

kubectl -n ${NAMESPACE} wait --for=condition=Programmed=true kongservice --all --timeout -1s test1
kubectl -n ${NAMESPACE} wait --for=condition=Programmed=true kongroute --all --timeout -1s test1
kubectl -n ${NAMESPACE} delete kongservice test1
kubectl -n ${NAMESPACE} wait --for=delete kongroute --all --timeout -1s test1
```

**Comment by randmonkey** [comment]
> ```#!/bin/bash
> 
> NAMESPACE=default
> 
> kubectl apply -f - <<EOF
> kind: KongService
> apiVersion: configuration.konghq.com/v1alpha1
> metadata:
>   name: test1
>   namespace: ${NAMESPACE}
> spec:
>   name: test1
>   host: example.com
>   controlPlaneRef:
>     type: konnectNamespacedRef
>     konnectNamespacedRef:
>       name: test1
> ---
> kind: KongRoute
> apiVersion: configuration.konghq.com/v1alpha1
> metadata:
>   name: test1
>   namespace: ${NAMESPACE}
> spec:
>   name: test1
>   protocols:
>   - http
>   hosts:
>   - example1.com
>   serviceRef:
>     type: namespacedRef
>     namespacedRef:
>       name: test1
> EOF
> 
> kubectl -n ${NAMESPACE} wait --for=condition=Programmed=true kongservice --all --timeout -1s test1
> kubectl -n ${NAMESPACE} wait --for=condition=Programmed=true kongroute --all --timeout -1s test1
> kubectl -n ${NAMESPACE} delete kongservice test1
> kubectl -n ${NAMESPACE} wait --for=delete kongroute --all --timeout -1s test1


I used the image built from the latest `main` (image tag `kong/gateway-operator-oss:v1.4.0-rc.0-10-g550c937c`) and ran the script you provided. The process stuck on the last step of waiting for the `KongRoute` to be deleted.  After force terminating the script, you can use `kubectl get kongservices test1 -o yaml`, you will see 

```
- lastTransitionTime: "2024-10-25T03:04:53Z"
    message: |-
      failed to delete KongService on Konnect: API error occurred: Status 400
      {"code":3,"message":"data constraint error","details":[{"@type":"type.googleapis.com/kong.admin.model.v1.ErrorDetail","type":"ERROR_TYPE_REFERENCE","messages":["constraint failed (type: foreign) as route references this value"]}]}
    observedGeneration: 2
    reason: KonnectAPIOpFailed
    status: "False"
    type: Programmed

```
in the conditions.

**Comment by randmonkey** [comment]
@pmalek I updated the script for reproducing (and looking at the "final" status of `KongService` if it has not been correctly deleted)
```
#!/bin/bash

NAMESPACE=default

kubectl apply -f - <<EOF
kind: KongService
apiVersion: configuration.konghq.com/v1alpha1
metadata:
  name: test1
  namespace: ${NAMESPACE}
spec:
  name: test1
  host: example.com
  controlPlaneRef:
    type: konnectNamespacedRef
    konnectNamespacedRef:
      name: test1
---
kind: KongRoute
apiVersion: configuration.konghq.com/v1alpha1
metadata:
  name: test1
  namespace: ${NAMESPACE}
spec:
  name: test1
  protocols:
  - http
  hosts:
  - example1.com
  serviceRef:
    type: namespacedRef
    namespacedRef:
      name: test1
EOF

kubectl -n ${NAMESPACE} wait --for=condition=Programmed=true kongservice/test1 --timeout=10s
kubectl -n ${NAMESPACE} wait --for=condition=Programmed=true kongroute/test1 --timeout=10s
kubectl -n ${NAMESPACE} delete kongservice test1
kubectl -n ${NAMESPACE} wait --for=delete kongservice/test1 --timeout=30s || kubectl -n ${NAMESPACE} get kongservice test1 -o yaml     
```
Also I found such log 
```
{"level":"error","ts":"2024-10-25T03:37:17Z","msg":"Reconciler error","controller":"KongRoute","controllerGroup":"configuration.konghq.com","controllerKind":"KongRoute","KongRoute":{"name":"test1","namespace":"default"},"namespace":"default","name":"test1","reconcileID":"1493b8f4-28de-44e1-8c6f-6014e65a26ee","error":"failed to delete default/test1: kongroutes.configuration.konghq.com \"test1\" is forbidden: User \"system:serviceaccount:kong-system:gateway-operator-controller-manager\" cannot delete resource \"kongroutes\" in API group \"configuration.konghq.com\" in the namespace \"default\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/yitao/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/yitao/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/yitao/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
```
Looks like it is brought by misconfiguration of rbac.
