### ISSUE TITLE
DataPlane replicas should not be set by Gateway controller when scaling is enabled 

### ISSUE THREAD

**Issue by czeslavo** [Kong/kong-operator#78]
## Current Behavior

When deploying a Gateway with the following DataPlaneOptions:

```yaml
    deployment:
      scaling:
        horizontal:
          minReplicas: 2
          maxReplicas: 5
          metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 50
          behavior:
            scaleUp:
              stabilizationWindowSeconds: 1
              policies:
              - type: Percent
                value: 100
                periodSeconds: 10
              - type: Pods
                value: 5
                periodSeconds: 10
              selectPolicy: Max
            scaleDown:
              stabilizationWindowSeconds: 1
              policies:
              - type: Percent
                value: 100
                periodSeconds: 10
      podTemplateSpec:
        spec:
          containers:
          - name: proxy
            image: kong:3.6.1
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "1024Mi"
                cpu: "1000m"
            env:
            - name: KONG_ROUTER_FLAVOR
              value: expressions
```
The Gateway controller [sets DP replicas to 1](https://github.com/Kong/gateway-operator/blob/830abd5a06b3801923a92e6f49457092478b8e57/controllers/gateway/controller.go#L628) when they're `nil` in the GatewayConfiguration. 

## Expected Behavior

If `GatewayConfiguration` specifies a non-empty `deployment.scaling` field in `DataPlaneOptions`, the Gateway controller should not populate the `replicas` field in `DataPlane` specification, even if it's `nil` in `GatewayConfiguration`.

## Operator Version

v1.2
