### ISSUE TITLE
When a target of an unmanaged `KongPluginBinding` is deleted, the `KongPluginBinding` is deleted without logs mentioning that

### ISSUE THREAD

**Issue by randmonkey** [Kong/kong-operator#786]
## Current Behavior

When I create a `KongPluginBinding` and delete one of the entities in its `targets`, for example:
```
apiVersion: configuration.konghq.com/v1alpha1
kind: KongPluginBinding
metadata:
  name: plugin-binding-kongservice
spec:
  controlPlaneRef:
    type: konnectNamespacedRef
    konnectNamespacedRef:
      name: test1
  pluginRef:
    name: rate-limit-5-min
  targets:
    serviceRef:
      name: service-1
      kind: KongService
      group: configuration.konghq.com
    consumerRef:
      name: consumer-1
```
When I delete the `KongConsumer`, the consumer gets deleted in Konnect as well as the plugin. After a `Reconciliation Error` telling that failed to update the plugin in Konnect because the plugin's foreign entity is not found, the `KongPluginBinding` is also deleted without a log to mention this.

## Expected Behavior

- Updating the status of `KongPluginBinding` to show that one of referenced targets is not found. Or
- Deleting the `KongPluginBinding` and add logs or k8s events to notice that it was deleted
