### ISSUE TITLE
dataPlaneOptions ingress `type: ClusterIP` does not produce a valid service definition for the dataplane.

### ISSUE THREAD

**Issue by scottaubrey** [Kong/kong-operator#811]
## Current Behavior

Setting a data plane ingress type to `type: ClusterIP` should be possible, but fails to deploy. The controller manager produces an error similar to :

```
"Service \"dataplane-ingress-epp-server-gateway-xj9d2-57ckv\" is invalid: spec.externalTrafficPolicy: Invalid value: \"Cluster\": may only be set for externally-accessible services"
```

## Expected Behavior

Deployed gateway serving internal cluster traffic only.

## Steps To Reproduce

Specify the service type on a `GatewayConfiguration` object:
```
spec:
  dataPlaneOptions:
    network:
      services:
        ingress:
          externalTrafficPolicy: null
          type: ClusterIP # internal gateway only
```

This seems to be caused by the changes made [here](https://github.com/Kong/gateway-operator/pull/241), and in particular the defaulting to Cluster type done [here](https://github.com/Kong/gateway-operator/blob/7d67f04feaafc31146b02b87a3fcd363014319cc/pkg/utils/kubernetes/resources/services.go#L117). Setting `spec.dataPlaneOptions.network.services.ingress.externalTrafficPolicy` to any valid value does not produce a valid gateway service definition while type is `ClusterIP`.

## Operator Version
1.3

## `kubectl version`
> kubectl version
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.30.4-eks-a737599
