### ISSUE TITLE
Konnect entities: implement `konnectID` control plane ref

### ISSUE THREAD

**Issue by pmalek** [Kong/kong-operator#922]
### Problem statement

Konnect entities (implemented in #370) provided support for referencing Konnect ControlPlanes via `konnectNamespacedRef`.

A separate type of reference - `konnectID` - [has also been prepared](https://github.com/Kong/kubernetes-configuration/blob/96347fff10fbac9a0f1463758be82d1942890012/api/configuration/v1alpha1/konnect_controlplaneref_types.go#L39-L42) but not implemented yet.

This issue tracks the effort of implementing that so that users can reference Konnect CPs by ID:

```
kind: KongService
apiVersion: configuration.konghq.com/v1alpha1
metadata:
  name: service-2
  namespace: default
spec:
  name: service-3
  host: example.com
  controlPlaneRef:
    type: konnectID
    konnectID: 2b08d44d-d0f9-4cfc-b1d8-111111111
```

### Acceptance criteria

- [ ] As a user I can use `konnectID` control plane reference for binding my entities to Konnect CPs  by ID.

**Comment by czeslavo** [comment]
Realised that https://github.com/Kong/gateway-operator/issues/460 is required for this one to be implemented properly. Marking as blocked for now.

**Comment by pmalek** [comment]
> Realised that #460 is required for this one to be implemented properly. Marking as blocked for now.

Hm, does it really block this one? Referencing a CP using a Konnect ID does not imply adopting anything, right? Or am I missing something here?

**Comment by czeslavo** [comment]
> Hm, does it really block this one? Referencing a CP using a Konnect ID does not imply adopting anything, right? Or am I missing something here?

My understanding is that the goal of this issue is to allow using a CP that was created in Konnect manually. Otherwise, there's not much value in this feature alone, I'd say (if I created a CP by defining a K8s object, then I can refer to it by name/namespace just fine). Anyway, maybe you're right. We can implement this without the adoption mechanism, while the adoption will make this more useful.

**Comment by randmonkey** [comment]
Re-open it since we have reverted the support of `konnectID` CP ref.

**Comment by sandromodarelli** [comment]
i was discussing with @mlavacca about considering the creation of a "dummy" `KonnectGatewayControlPlane` where we setup the plain ID as a spec:
```
apiVersion: konnect.konghq.com/v1alpha1
kind: KonnectGatewayControlPlane
metadata:
  name: dummy-cp
spec:
  konnect:
    id: 8c13a9be-21b1-43fa-b401-4e62b5290302 # this is the CP id on konnect
    authRef:
      name: konnect-api-auth-dev-1
status:
  id: 8c13a9be-21b1-43fa-b401-4e62b5290302 # reconciliation will only take care of setting the ID in the status
```
in this way a k8s team can receive from a platform team the ID of the CP, set it up as a dummy CP, attach to it the `authRef` and entities will belong this the dummy CP as today
